#Project 1 : Create a basic debian box 

# VM Configuration

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.box_version = "202510.26.0"
  config.vm.hostname = "debian-base"


# Provider Configuration

  config.vm.provider "virtualbox" do |vb|   
    vb.memory = "1024"
    vb.cpus = 1
    vb.gui = false
end

# Private Network Configuration

  config.vm.network "private_network", ip: "192.168.56.10",
    virtualbox__intnet: true


# Provisioning personalised message in /etc/motd
  config.vm.provision "shell", inline: <<-SHELL
    echo "VM TP – Debian Base" > /etc/motd
  SHELL
  
end